[package]
name = "visconc"
version = "0.1.0"
authors = ["Skyler Calaman <54462713+Blckbrry-Pi@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"